name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: xt0rted/setup-dotnet@v1.5.0
      with:
        dotnet-version: 7.0.201
    - name: Build
      run: dotnet build src/FluentvalidationBR.Extensions.sln
    - name: Test
      run: dotnet test src/FluentvalidationBR.Extensions.sln
